### ISSUE TITLE
Add "Sign Up" functionality

### ISSUE THREAD

**Issue by Ulydev** [themeteorchef/building-a-blog-with-react#1]
Hello, TheMeteorChef!
First of all, I'd like to thank you for all your superb tutorials. I just got started with Meteor and this helps me so much.
I would like to make a blog using your "Base" project, and this repo seemed like the way to do it.

I am having an error when trying to sign up (through the login page), it redirects to a 404 error.
Do you have any idea on how to enable both Login and Register on this project?

Thanks in advance, and keep up the awesome work!

**Comment by themeteorchef** [comment]
Hey @Ulydev! 

This was disabled to play along with the story for this recipe. You can, however, [grab it on the base-react branch](https://github.com/themeteorchef/base/blob/base-react/client/components/views/signup.jsx) :) Just copy the code their and add `signup.jsx` to your `/client/components/views` directory and it should work. Note: you _will_ need to add a route to `/both/routes/public.jsx` that points to the `<Signup />` component.

**Comment by Ulydev** [comment]
Awesome, thanks for the fast reply!
